### ISSUE TITLE
Using this library with SugarCRM 7

### ISSUE THREAD

**Issue by nilesh-shah** [mattkol/SugarSharpClient#1]
Hello @mattkol 
I would like to know if this library is actively maintained and can be used to access V10 REST APIs for SugarCRM 7.x

We are in process of implementing a SugarCRM connector and I would like to get some help here. If you have come across any good documentation, examples or any other open source libraries which can help us doing that, Please share the information.

Thank you.

**Comment by mattkol** [comment]
Hi,
Yes it is actively maintained-  no more development planned, but issues and improvements.

This project is focused on SugarCrm Rest V4. This can be used for SugarCrm 6.5x. V10 is out of scope. However the project can be leveraged for V10.

There are a few github projects that have addressed V10. I am currently on vacation when I am fully back online I can point you to some.

Thanks.

**Comment by mattkol** [comment]
These are few github projects that address V10
https://github.com/dlively1/SugarSharp
https://gist.github.com/elchele/e4be253a38e2223add1fdc642fb4277e

**Comment by nilesh-shah** [comment]
Thank you @mattkol
