### ISSUE TITLE
How create link between entries in SuiteCRM 7.x

### ISSUE THREAD

**Issue by Conquistador** [mattkol/SugarSharpClient#2]
Hi @mattkol,

Can you show, how create link between entries in modules (for example Accounts and Contacts) with your library ?

**Comment by mattkol** [comment]
Sorry for the late response.
Please check:
https://github.com/mattkol/SugarRestSharp/wiki/Linked-Modules-1

There are also other examples at:
https://github.com/mattkol/SugarRestSharp/wiki/Linked-Modules-2
https://github.com/mattkol/SugarRestSharp/wiki/Query-Options-3
