### ISSUE TITLE
Put a meeting on user's calendar

### ISSUE THREAD

**Issue by luscala** [mattkol/SugarSharpClient#4]
Hi @mattkol,
I am using SugarRestSharp to pragmatically create meetings on my SuiteCRM installation. Each meeting is assigned to a defined user, but I can't see them on the calendar. I know that it's needed to place a relationship between meeting and user, via meetings_users table. How can I archieve that with SugarRestSharp?

Thanks
chogori

**Comment by mattkol** [comment]
Sorry for the late response.

All linked relationships are achieved using custom models with Linked Modules. 
Please see examples @ [Linked Modules 1](https://github.com/mattkol/SugarRestSharp/wiki/Linked-Modules-1) [Linked Modules 1](https://github.com/mattkol/SugarRestSharp/wiki/Linked-Modules-2) [Linked Modules 3](https://github.com/mattkol/SugarRestSharp/wiki/Linked-Modules-3)

Alternatively if you know the Ids of users and meetings to join you can treat MeetingUsers as a module and save that. [MeetingUsers](https://github.com/mattkol/SugarRestSharp/blob/master/SugarRestSharpSolution/SugarRestSharp/SugarCrmModels/MeetingsUsers.cs)

Please let me know if this helps.

**Comment by luscala** [comment]
Yes, I know ids of meeting and assigned-user that I want to link. In particular,

            Meeting meeting = new Meeting();
            // meeting information here...

            MeetingsUsers meetingUser = new MeetingsUsers();
            meetingUser .MeetingId = meeting.Id;
            meetingUser .UserId = assignedUser.Id;

            request = new SugarRestRequest("MeetingsUsers", RequestType.Create);
            request.Parameter = meetingUser;
            response = client.Execute(request);

JsonRawResponse says "Module Does Not Exist". Tryed with "meetings_users" instead of MeetingsUsers.
What's wrong?
Thanks

**Comment by mattkol** [comment]
I forgot to mention, the module must be valid "SugarCrm module" and meetings_users is not likely a valid module. Please try a call with get_available_modules (not implemented in SugarRestSharp, but done in [SugarOnRest](https://github.com/mattkol/SugarOnRest/blob/master/sugaronrest/src/main/java/com/sugaronrest/restapicalls/methodcalls/GetAvailableModules.java)) to get list of available modules.

Meanwhile I believe you need to implement "set_relationship", which is not implemented here. SugarRestSharp only implemented these methods -get_entry, get_entry_list, set_entry, set_entries- to achieve basic CRUD operation. So I would say not currently in scope of this project. [Please see Readme](https://github.com/mattkol/SugarRestSharp).

However, using what has been done here, it will be easy to extend at your end, and if you are comfortable with this I will accept a PR. These are the links from SugarCrm site: [set_relationship](http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Web_Services/Method_Calls/set_relationship/) -and- [set_relationships](http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Web_Services/Method_Calls/set_relationships/)

You can try modify [InsertEntry](https://github.com/mattkol/SugarRestSharp/blob/master/SugarRestSharpSolution/SugarRestSharp/RestApiCalls/MethodCalls/InsertEntry.cs) for that.

If I need to make change to add this feature, I can do it weekend. 
Please let me know if you need more info before then.
Thanks.

**Comment by luscala** [comment]
Ok, done with a new InsertRelationship class (with InsertRelatioshipResponse, new RequestType...). It works, but there's a problem when deleting (but it seems to be a permission problem). I don't know how git works, but if you want I can submit my changes.

**Comment by mattkol** [comment]
Thanks. That is great.
You can fork and submit PR but if you want you can post entire code here.
I will merge over the weekend.
Thanks for your help and contribution to the project.
