### ISSUE TITLE
Response Data Limited To 100

### ISSUE THREAD

**Issue by Manthan2611** [mattkol/SugarSharpClient#7]
Hi,

When i try to trigger the following code for bulk read all my existing case on debugging the result only show the 100 data of case.
How to get all the cases which are present in the SugarCRM? 

`var client = new SugarRestClient(url, username, password);
 var request = new SugarRestRequest(RequestType.BulkRead);
 SugarRestResponse response = client.Execute<Case>(request);
List<Case> cases = (List<Case>)response.Data;`

Thanks & Regards,
Manthan Patel

**Comment by mattkol** [comment]
This limit can be changed only on the server.

_"A maximum amount of records is configured by default to 100. It can be configured through the config_override.php option $sugar_config['bulk_import_settings']['max_records']"_

https://github.com/sugarcrmlabs/BulkImport

**Comment by Manthan2611** [comment]
Hi there, Thanks for the update
